version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.14.0
    restart: on-failure:0
    ports:
     - "80:8080"
    volumes:
      - /var/weaviate:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      ENABLE_MODULES: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
      CLUSTER_HOSTNAME: 'node1'
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-msmarco-distilroberta-base-v2
    environment:
      ENABLE_CUDA: 1 # set to 1 to enable
      NVIDIA_VISIBLE_DEVICES: all # enable if running with CUDA
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - 'gpu'
            - 'utility'
            - 'compute'
